name: AndroidBuild
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'



      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidCICD.apk
          path: app\build\outputs\apk\debug\app-debug.apk
